name: CI com Snyk Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  snyk_scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    permissions:
      # Permissão necessária para o Snyk postar o resultado
      pull-requests: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Roda o Snyk para encontrar vulnerabilidades de segurança (SAST)
        # actions oficial do Snyk
        uses: snyk/actions/setup@master
      - run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
